version: "3"

services:

  app:
    build: ./php
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html

  mysql:
    build: ./mysql
    ports:
      - 3333:3306
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: pwd

volumes:
  db-data: